version: '3.4'

services:
  application:
    container_name: asinsum
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - asinsum-network
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: asnisum
      MYSQL_ROOT_PASSWORD: drowssap
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    networks:
      - asinsum-network

networks:
  asinsum-network:
    driver: bridge