version: '3.4'

services:
  application:
    image: asinsum
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: asnisum
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306